services:
    # _defaults:
    #     bind:
    #         PoP\Hooks\HooksAPIInterface: '@hooks_api'
    #         PoP\Translation\TranslationAPIInterface: '@translation_api'
    #         PoP\ComponentModel\Schema\FeedbackMessageStoreInterface: '@feedback_message_store'
    #         PoP\QueryParsing\QueryParserInterface: '@query_parser'

    type_registry:
        class: \PoP\GraphQL\Registries\TypeRegistry
        public: true

    field_registry:
        class: \PoP\GraphQL\Registries\FieldRegistry
        public: true

    PoP\GraphQL\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\GraphQL\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
