services:
    # _defaults:
    #     bind:
    #         PoP\Hooks\HooksAPIInterface: '@hooks_api'
    #         PoP\Translation\TranslationAPIInterface: '@translation_api'
    #         PoP\ComponentModel\Schema\FeedbackMessageStoreInterface: '@feedback_message_store'
    #         PoP\QueryParsing\QueryParserInterface: '@query_parser'

    PoP\GraphQL\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\GraphQL\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
